### ISSUE TITLE
Your component is featured in one of Vaadin blogs

### ISSUE THREAD

**Issue by binhbbbb** [balint777/b7-carousel#2]
Hi balint777,

My name is Binh Bui, the Marketing Community Specialist of Vaadin. Recently, I tested your component and I think b7-carousel is a super cool component. I featured it on the blog [8 best Polymer carousel web components for your next web app](https://vaadin.com/blog/10-best), make sure you check it out.

Also, it would be great if we can have some words from the original author under the blog comment section, or in this [tweet](https://twitter.com/binhbbbb/status/991599744215666688), or even better, both 😉

Cheers!

**Comment by balint777** [comment]
Dear binhbbbb,
First of all thank you for featuring this component on vaadin.com. Your pull request #1 has been accepted. Please note that based on your review
* I have added keyboard paging support to the component since [v0.2](https://github.com/balint777/b7-carousel/releases/tag/v0.2.0)
* As for the mouse-drag support I do not know of any decently performing way to support this on PC or a notebook, although on touch devices the component does support native kinnetic touch scrolling!
* Mobile support was a key goal, and should be working on at least latest Safari and Chrome, if it does  not - issues are welcome.
I did not find a way to update the published element on vaadin directory, also any guidance would be welcome there.

**Comment by binhbbbb** [comment]
Hey,

Good work on adding those features. I am afraid I don't know any mouse-drag support neither (not a technical guy much).

For the Vaadin Directory, you don't need to do anything to update them. We update it every so if you have a new release, the Directory will automatically fetch that for you. At the moment, we temporarily disable users self-adding web components but feel free to give me a request and I will deploy that for you.

Regards,
Binh
